config/routes.rb
Rails.application.routes.draw do
  get 'home/index'

  devise_for :users
  resources :events
  get '/calendar', to: 'events#calendar'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root to: "home#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/event.rb
class Event < ApplicationRecord
  has_and_belongs_to_many :users
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_and_belongs_to_many :events
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_event, only: [:show, :edit, :update, :destroy]

  # GET /events
  # GET /events.json
  def index
    @events = Event.all
    @users = User.all
  end

  def calendar
    @events = Event.all
    @users = User.all
    @events_by_date = @events.group_by { |event| event.start_datetime.to_date }
    @current_date = params[:date] ? Date.parse(params[:date]) : Date.today
  end

  # GET /events/1
  # GET /events/1.json
  def show
  end

  # GET /events/new
  def new
    @event = current_user.events.build
    #@event = Event.new
  end

  # GET /events/1/edit
  def edit
  end

  # POST /events
  # POST /events.json
  def create
    @event = current_user.events.build(event_params)
    #@event = Event.new(event_params)

    respond_to do |format|
      if @event.save
        format.html { redirect_to @event, notice: 'Event was successfully created.' }
        format.json { render :show, status: :created, location: @event }
      else
        format.html { render :new }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /events/1
  # PATCH/PUT /events/1.json
  def update
    respond_to do |format|
      if @event.update(event_params)
        format.html { redirect_to @event, notice: 'Event was successfully updated.' }
        format.json { render :show, status: :ok, location: @event }
      else
        format.html { render :edit }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /events/1
  # DELETE /events/1.json
  def destroy
    @event.destroy
    respond_to do |format|
      format.html { redirect_to events_url, notice: 'Event was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_event
      @event = Event.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def event_params
      params.require(:event).permit(:name, :location, :start_datetime, :end_datetime, :description, :registration_limit)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController

  private
    def sign_up_params
      params.require(:user).permit(:first_name, :last_name, :email, :password, :password_confirmation)
    end

    def account_update_params
      params.require(:user).permit(:first_name, :last_name, :email, :password, :password_confirmation, :current_password)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper


end

# Add to config/initializers/form.rb or the end of app/helpers/application_helper.rb
module ActionView
  module Helpers
    class FormBuilder
      def date_select(method, options = {}, html_options = {})
        existing_date = @object.send(method)

        # Set default date if object's attr is nil
        existing_date ||= Time.now.to_date

        formatted_date = existing_date.to_date.strftime("%F") if existing_date.present?
        @template.content_tag(:div, :class => "input-group") do
          text_field(method, :value => formatted_date, :class => "form-control datepicker", :"data-date-format" => "YYYY-MM-DD") +
          @template.content_tag(:span, @template.content_tag(:span, "", :class => "glyphicon glyphicon-calendar") ,:class => "input-group-addon")
        end
      end

      def datetime_select(method, options = {}, html_options = {})
        existing_time = @object.send(method)

        # Set default date if object's attr is nil
        existing_date ||= Time.now

        formatted_time = existing_time.to_time.strftime("%F %I:%M %p") if existing_time.present?
        @template.content_tag(:div, :class => "input-group") do
          text_field(method, :value => formatted_time, :class => "form-control datetimepicker", :"data-date-format" => "YYYY-MM-DD hh:mm A") +
          @template.content_tag(:span, @template.content_tag(:span, "", :class => "glyphicon glyphicon-calendar") ,:class => "input-group-addon")
        end
      end
    end
  end
end

app/helpers/calendar_helper.rb
module CalendarHelper
  def calendar(date = Date.today, &block)
    Calendar.new(self, date, block).table
  end

  class Calendar < Struct.new(:view, :date, :callback)
    HEADER = %w[Sunday Monday Tuesday Wednesday Thursday Friday Saturday]
    START_DAY = :sunday

    delegate :content_tag, to: :view

    def table
      content_tag :table, class: "calendar" do
        header + week_rows
      end
    end

    def header
      content_tag :tr do
        HEADER.map { |day| content_tag :th, day }.join.html_safe
      end
    end

    def week_rows
      weeks.map do |week|
        content_tag :tr do
          week.map { |day| day_cell(day) }.join.html_safe
        end
      end.join.html_safe
    end

    def day_cell(day)
      content_tag :td, view.capture(day, &callback), class: day_classes(day)
    end

    def day_classes(day)
      classes = []
      classes << "today" if day == Date.today
      classes << "notmonth" if day.month != date.month
      classes.empty? ? nil : classes.join(" ")
    end

    def weeks
      first = date.beginning_of_month.beginning_of_week(START_DAY)
      last = date.end_of_month.end_of_week(START_DAY)
      (first..last).to_a.in_groups_of(7)
    end
  end
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/events/_form.html.erb
<%= form_for(event) do |f| %>
  <% if event.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(event.errors.count, "error") %> prohibited this event from being saved:</h2>

      <ul>
      <% event.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="row">
      <div class="col-lg-2">
          <div class="form-group">
            <%= f.label :name %>
            <%= f.text_field :name, class:"form-control" %>
          </div>

          <div class="form-group">
            <%= f.label :location %>
            <%= f.text_field :location, class:"form-control" %>
          </div>

          <div class="form-group">
            <%= f.label :start_datetime %>
            <%= f.datetime_select :start_datetime, class:"datetimepicker" %>
          </div>

          <div class="form-group">
            <%= f.label :end_datetime %>
            <%= f.datetime_select :end_datetime, class:"datetimepicker" %>
          </div>

          <div class="form-group">
            <%= f.label :description %>
            <%= f.text_area :description, class:"form-control" %>
          </div>

          <div class="form-group">
            <%= f.label :registration_limit %>
            <%= f.number_field :registration_limit, class:"form-control" %>
          </div>

          <div class="actions">
            <%= f.submit :class => "btn btn-default" %>
          </div>
      </div>
  </div>
<% end %>

<script>
  //$('.datetimepicker').datetimepicker();
  $('#event_start_datetime').datetimepicker();
  $('#event_end_datetime').datetimepicker({
      useCurrent: false //Important! See issue #1075
  });
  $("#event_start_datetime").on("dp.change", function (e) {
      $('#event_end_datetime').data("DateTimePicker").minDate(e.date);
  });
  $("#event_end_datetime").on("dp.change", function (e) {
      $('#event_start_datetime').data("DateTimePicker").maxDate(e.date);
  });
</script>

app/views/events/calendar.html.erb
<div id="events">
  <h2 id="month">
    <%= link_to "<", date: @current_date.prev_month %>
    <%= @current_date.strftime("%B %Y") %>
    <%= link_to ">", date: @current_date.next_month %>
  </h2>
  <h3 style="text-align: center;"><%= link_to "Today", date: Date.today %></h3>
  <%= calendar @current_date do |date| %>
    <%= date.day %>
    <% if @events_by_date[date.to_datetime] %>
      <div class='event-clickable'>
        <% @events_by_date[date].each do |event| %>
          <% if event.end_datetime.to_date < Date.today %>
            <li class="past-event"><%= link_to event.name, event %></li>
          <% else %>
            <li class="future-event"><%= link_to event.name, event %></li>
          <% end %>
        <% end %>
      </div>
    <% end %>
  <% end %>
</div>


<div id="selected-event-info">

</div>

app/views/events/edit.html.erb
<h1>Editing Event</h1>

<%= render 'form', event: @event %>

<%= link_to 'Show', @event, class: 'btn btn-default' %>
<%= link_to 'Back', events_path, class: 'btn btn-default' %>

app/views/events/index.html.erb
<h1>All Events</h1>

<table class="table table-striped">
  <thead>
    <tr>
      <th>Name</th>
      <th>Location</th>
      <th>Description</th>
      <th>Start date</th>
      <th>End date</th>
      <th>Start time</th>
      <th>End time</th>
      <th>Registration Limit</th>
      <th>User</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @events.each do |event| %>
      <tr>
        <td><%= event.name %></td>
        <td><%= event.location %></td>
        <td><%= event.description %></td>
        <td><%= event.start_datetime.strftime("%b %d, %Y") %></td>
        <td><%= event.end_datetime.strftime("%b %d, %Y") %></td>
        <td><%= event.start_datetime.strftime("%H:%M") %></td>
        <td><%= event.end_datetime.strftime("%H:%M") %></td>
        <td><%= event.registration_limit %></td>
        <td><%= @users.find(event.user_id).email %></td>
        <td><%= link_to 'Show', event, class: "btn btn-default btn-sm" %></td>
        <% if @users.find(event.user_id) == current_user %>
          <td><%= link_to 'Edit', edit_event_path(event), class: "btn btn-default btn-sm" %></td>
          <td><%= link_to 'Destroy', event, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-sm btn-danger" %></td>
        <% else %>
          <td></td>
          <td></td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Event', new_event_path, class: "btn btn-default" %>

app/views/events/new.html.erb
<h1>New Event</h1>

<%= render 'form', event: @event %>

<%= link_to 'Back', events_path, class: "btn btn-default" %>

app/views/events/show.html.erb
<p>
  <strong>Name:</strong>
  <%= @event.name %>
</p>

<p>
  <strong>Location:</strong>
  <%= @event.location %>
</p>

<p>
  <strong>Start datetime:</strong>
  <%= @event.start_datetime %>
</p>

<p>
  <strong>End datetime:</strong>
  <%= @event.end_datetime %>
</p>

<p>
  <strong>Description:</strong>
  <%= @event.description %>
</p>

<p>
  <strong>Registration limit:</strong>
  <%= @event.registration_limit %>
</p>

<p>
  <strong>RSVP</strong>
  <%= @event.registration_limit %>
</p>

<%= link_to 'Edit', edit_event_path(@event), class: 'btn btn-default' %>
<%= link_to 'Back', events_path, class: 'btn btn-default' %>

app/views/home/index.html.erb
<h1>Event Registration System</h1>
<p>Created by Timothy Chen</p>

<br />

<% if current_user %>
  <h2>My Profile</h2>
  <%= current_user.first_name %> <%= current_user.last_name %><br />
  <%= current_user.email %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Event Registration System</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

    <div id="wrapper">
      <%#= render "shared/navbar" %>
        <div id="page-wrapper">
            <div class="container-fluid">

              <ul class="nav navbar-nav">
                <li><%= link_to "Home", home_index_path %></li>
                <li><%= link_to "Calendar", calendar_path %></li>
                <li><%= link_to "Events Listing", events_path %></li>
                <% if current_user %>
                  <li><%= link_to "Logout", destroy_user_session_path, method: :delete %></li>
                <% else %>
                  <li><%= link_to "Login", new_user_session_path %></li>
                <% end %>
              </ul>


              <section class="row">
                <div class="col-lg-12">
                  <% flash.each do |key, value| %>
                    <br />
                    <div class="alert alert-info alert-dismissable"><%= value %></div>
                  <% end %>
                </div>
              </section>

              <section class="row">
                  <div class="col-lg-12" id="main_content">
                      <%= yield %>
                  </div>
              </section><!-- /.row -->

              <div class="row"><br /><br /></div><!-- /.row -->

            </div><!-- /.container-fluid -->
        </div><!-- /#page-wrapper -->
    </div><!-- /#wrapper -->

  </body>
</html>